### ISSUE TITLE
User Registration- Autofill business name

### ISSUE THREAD

**Issue by priyankshukla** [OrderMail/blacklabel#12]
### Acceptance Criteria:
1. There should be a user registration screen
2. Business name field must be there
3. Autofill functionality must be enable, after tying 3 business name characters at-least
4. Autofill should show only those business name, which are present in blacklabel database

~~5.  'New business registration' link must be available, if the entered business doesn't exist in database (minimum 3 characters are required)~~

### Subtasks

- [x] Design a Screen Wireframe
- [x] Review the mockup 
- [x] Develop the backend service to enable autofill functionality
- [x] Integrate
- [x] Create dropdown
- [x] Replace dropdown by autocomplete widget
- [ ] Writing test cases

**Comment by vikasagarwal** [comment]
Updated requirement

**Comment by vikasagarwal** [comment]
I used Angular Bootstrap typeahead, which I found had certain shortcomings. I had to work around those but managed to complete this. 

@priyankshukla Please review

**Comment by priyankshukla** [comment]
@vikasagarwal I am unable to register a new user, and getting below error (in console) while doing so:
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

**Comment by vikasagarwal** [comment]
Did you try selecting the business name by hitting enter on the keyboard? Are you able to test it on another browser? If not, @naveen can you test this?

**Comment by vikasagarwal** [comment]
Please git stash your local changes and then try again once.

**Comment by vikasagarwal** [comment]
I tested again in Firefox as well as in Chromium. I'm able to sign up from both the browsers successfully and there is no error. However, in Firefox, the issue is, the selected business name doesn't appear even after it has been selected. This issue isn't present when I test using Chromium.

@priyankshukla I suggest undo all your changes locally and re-test.

####Known Issue ####
User would need to hit enter instead of a mouse click to make a selection from the auto-suggest list. This is an issue with the version of Angular Bootstrap we're using. We will need to resolve it separately.

**Comment by vikasagarwal** [comment]
We are putting this on hold because of its dependency on Angular-bootstrap library. This bug #24  needs to be resolved before the launch but currently, deprioritizing.
