### ISSUE TITLE
User Registration- Placing registration functionality on 'home' page right panel

### ISSUE THREAD

**Issue by priyankshukla** [OrderMail/blacklabel#13]
### Acceptance Criteria:
1. There should be a 'Home page'
2. There should be a 'User Registration screen' on right panel
3. 'Sing-up' link must be hidden on 'Home' and 'logged-in' screen
4. 'Sing-up' link must be enable/visible on all the screen except  'Home' and 'logged-in' screen

### Subtasks

- [ ] Design the 'Home' page along with 'User Registration' page
- [ ] Handling enable/disable 'sign-up' link on header
- [ ] Integrate
- [ ] Writing test cases

**Comment by amit-k86** [comment]
This is the sign up page and not the Home Screen. Home Screen to be made later.
