### ISSUE TITLE
Store application session values using Redis.

### ISSUE THREAD

**Issue by priyankshukla** [OrderMail/blacklabel#32]
Use Redis to store persistent values.

### SubTasks:
- [x] Installing Redis server
- [x] Testing Redis
- [x] Documenting installation steps
- [x] Documenting the setup steps

**Comment by vikasagarwal** [comment]
Thanks for creating this story, Priyank. Please keep all the documentation
related to this as one of the subtasks. We probably need this documentation
to be available on our Google site.



On Tue, Mar 24, 2015 at 4:12 PM, Priyank Shukla <notifications@github.com>
wrote:

> Use Redis to store persistent values.
> SubTasks:
>
>    -  Installing Redis server
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OrderMail/blacklabel/issues/32>.
>



-- 
Best Cricket T20 Coverage on:
http://cricket-t20.com

**Comment by priyankshukla** [comment]
Link to install Redis server:
http://grainier.net/how-to-install-redis-in-ubuntu/

Link to uninstall Redis server
http://grainier.net/how-to-uninstall-redis-server-from-ubuntu/

**Comment by priyankshukla** [comment]
I documented and published the redis installation/uninstallation steps on below url:
https://sites.google.com/site/freakyorder/home/redis

**Comment by priyankshukla** [comment]
I successfully tested the redis session..

Here are the stepst o test the redis:
1. Install the Redis on your machine (https://sites.google.com/site/freakyorder/home/redis)
2. Start Redis server (sudo service redis_6379 start)
Fyr, stopping the redis server-  
     sudo service redis_6379 stop
3. Add an entry in package.json (main module) for redis session
 "redis" : "0.8.2"
4. npm install
5. bower install
6. bower install bootstrap
7. Create Redis and Client instances
 (below code will go to Node controller where we are going to use Redis)
  var redis = require('redis');
  var client = redis.createClient();
8. Set the value in redis by using client, make sure we have defined redis and client instances  earlier (step-7)  
 client.set(<key>, <value>, function (error, result) {
    if (error !== null) 
      console.log('error: ' + error);
    else {
      console.log('The value of key is : ' + <value>);
      }
    });
9. Retrieves the session by using <key>, make sure we have defined redis and client instances  earlier (step-7)
 client.get(<key>, function (error, val) {
  if (error !== null) 
    console.log('error: ' + error);
  else {      console.log('The value for this key is ' + val);}
  });
10. To retrieve the session values, we need to define the factory or service to call the node controller function (step-9) anywhere in the project.

**Comment by priyankshukla** [comment]
I am closing this ticket as this has been successfully written and tested, I will be raising a separate call where it requires to implement.
