### ISSUE TITLE
User should be able to register

### ISSUE THREAD

**Issue by vikasagarwal** [OrderMail/blacklabel#4]
### Acceptance Criteria:
1. There should be a registration screen
2. Fields should be:
   - Invididual or business
   - Name (first name and last name)
   -  Email
   - Business Name
   - Password and confirm password
   -  Admin Email (TBD)
3. Data should be available at the backend after the registration
4. Success message - "You have successfully signed up. Please check your email to activate your account."
### Subtasks
- [x] Design a Screen Wireframe
- [x] Review the mockup 
- [x] Create the screen
- [x] Develop the backend service
- [x] Integrate
- [x] Writing test cases
