### ISSUE TITLE
User should receive an email verification notification

### ISSUE THREAD

**Issue by vikasagarwal** [OrderMail/blacklabel#5]
### Acceptance Criteria
 1. User receives an email after a successful sign up
 2. The Email should contain a link to allow activation of the account
 3. The link should open a page that confirms activation and shows the login page 
 
### Subtasks
- [x] Create the email text 
- [x] Design the activation page
- [ ] Develop and Test

**Comment by vikasagarwal** [comment]
This has been tested already. I am closing this story now.

### Technical Debt ###
Test cases need to be written
