### ISSUE TITLE
User should be able to login

### ISSUE THREAD

**Issue by vikasagarwal** [OrderMail/blacklabel#6]
## Acceptance Criteria
- User should be to login
- Opens a page having just the text 'dashboard' after login.
- Sign out button (non-functional)
## Subtasks
- [x] Design the login page
- [x] Develop the backend service
- [x] Integrate
- [x] Create the dashboard page having only a sign out button
- [x] Writing test cases
