### ISSUE TITLE
Forgot Password: User should be able to perform forgot password feature

### ISSUE THREAD

**Issue by priyankshukla** [OrderMail/blacklabel#8]
### Acceptance Criteria

- The 'Forgot Password' link should be accessible to user prior to login
- The 'Forgot Password' link opens a page having 'text field' (to enter email address).
- A page should have 'Send' button, this uses to send a password reset link on entered email address (by user).
- 'Mail successfully sent' message should appear, if user enters correct email address.
- 'Email does not exist' message should appear, if user enters incorrect email address.

### Subtasks

- [x] Design the Forgot Password page
- [x] Develop the backend service
- [x] Integrate
- [x] 'Mail successfully' message on UI
- [x] 'Email does not exist' message on UI

**Comment by priyankshukla** [comment]
Removed a subtask for writing testcases.
Also, going to check whether this functionality is working on master branch or not!

**Comment by priyankshukla** [comment]
Tested and verified that the forgot password functionality is working on master and staging branch, closing this ticket though.

Observation:
A user can access the forgot password functionality without getting activated! I think, that is not a problem since he/she requires to get activated before login (it is working).
